### ISSUE TITLE
How to correctly set up .classpath

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#1017]
The app email has a dependency to javax.activation and javax.mail. These are inherited from core-email.

However in eclipse the imported project reports errors despite the .classpath being manually updated to include phoebus-target.

![image](https://user-images.githubusercontent.com/2111304/70723038-42521780-1cc6-11ea-9114-e1ab37bbefc1.png)

Once I configure this as a maven project, the error disappears.

![image](https://user-images.githubusercontent.com/2111304/70723251-98bf5600-1cc6-11ea-9586-759d59a66e0b.png)

What am I doing wrong here...

**Comment by kasemir** [comment]
Not sure, but overall I think we're fine.

I simply import the projects via File, Import, General, Existing Projects into Workspace, using the .classpath file without changes, and see no error.

![email](https://user-images.githubusercontent.com/1932421/70726822-ad065180-1ccc-11ea-8fdb-c1d7594a179d.png)

Those classes where you get the error are resolved to the binary in dependencies/phoebus-target/target/lib/activation-1.1jar

==> I'm fine.

You prefer to import as maven projects, and the error disappears

==> You're fine


You might be able to fix the Eclipse problem by opening in an instance of Eclipse that doesn't have additional maven tools installed, and then might still have to 'Project/clean' just the affected project. I do get that type of error occasionally for the XML parser imports, and Project/clean' on just the affected project fixes it.
