### ISSUE TITLE
[QUESTION] Default save path

### ISSUE THREAD

**Issue by DorianHas** [ControlSystemStudio/phoebus#1133]
Hello there,

Is there a way to put a default path when saving SNAPSHOT, modified PLTs or creating OPIs ?

Currently the default path is : user.home, but I want it to be an absolute path I chose.

Regards

Dorian

**Comment by kasemir** [comment]
The default is the 'current' directory when you start phoebus.
So you can adjust your launcher script to `cd` to whatever directory you want as a default just before you invoke `java -jar ...`

**Comment by kasemir** [comment]
Does that answer your question? Can we close this issue?

**Comment by DorianHas** [comment]
Yes.

I thought I closed it.
