### ISSUE TITLE
Multiple VTypeHelpers

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#1146]
There are multiple VTypeHelper which could be combined into a single utility module which can be shared between multiple applications.

![image](https://user-images.githubusercontent.com/2111304/74419291-ac4a8280-4e17-11ea-9bd2-90701a195cbc.png)

My recommendation would be to create a core-vtype module

**Comment by georgweiss** [comment]
I will work on this.

**Comment by georgweiss** [comment]
Not sure why, but @shroffk's commits are not visible on ConstrolSystemStudio/phoebus.

**Comment by shroffk** [comment]
@georgweiss can we close this.
