### ISSUE TITLE
Displays with top level macros always open in new tab/window.

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1210]
When DockStage looks for open displays the below comparison (line 291) fails if a display has top level macros:
`if (input.equals(item.getInput()) &&
                            item.getApplication().getAppDescriptor().getName().equals(application_name))
                            return item;`
Root cause us that input is the URI without macros, while item.getInput() return the same URI, but augmented with macros.

**Comment by kasemir** [comment]
See #928

**Comment by georgweiss** [comment]
Not sure #928 applies. My point is that in DockStage an URI with macros is compared to an URI without macros, even though the two URIs represent the same OPI file.

**Comment by kasemir** [comment]
A display is identified by the file name and macros.
You want to open file "x".
A tab replies with "I am file x with macros M=V".
On one hand, they're different.
On the other hand, "M=V" could be the default macros, they they would end up being the same.

One fix would be that an attempt to open file "x" gets extended with the default macros, so you'd compare "I want to open file x with macros M=V" against "I am file x with macros M=V".

**Comment by georgweiss** [comment]
I do not think that is the issue.
The method DockStage#getDockItemWithInput is called with an URI that is constructed from a file path only, so macro information is not available. This URI is compared to the input field of an DockItemWithInput, where macros are appended (not default macros, though). To me this is inconsistent and confusing: depending on context the input URI may come with or without macros.
Attached screen shot from a debugging session  demonstrates my point.
<img width="1396" alt="Screenshot 2020-03-17 at 16 13 38" src="https://user-images.githubusercontent.com/35602960/76871316-2f258980-686b-11ea-8048-f2c93ff142d2.png">

**Comment by georgweiss** [comment]
I'd would appreciate some attention for this issue. I may be wrong, but in my view the root cause is that the implementation attempts to support both URIs and file paths depending on how a display is loaded. The data objects (e.g. DisplayInfo) when edit and runtime applications are started are not created in a consistent manner between those cases. Ultimately this results in a comparison in DockStage that will never be meaningful.
Also detected that a file URI specified as the quoted value for the resource application argument does not work. The quotes would be needed to support space characters.

**Comment by georgweiss** [comment]
Will not fix this. Closing due to lack of input.
