### ISSUE TITLE
Handle failed log entry submissions. 

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1245]
The log entry UI shall not close automatically unless the submission succeeds. Otherwise user shall be notified about reason.

**Comment by shroffk** [comment]
Thanks, in particular the most common error tends to be authentication... a mis typed password... in such a case the closing of the log entry results in a loss of users efforts (typing, adding images, etc..)

With this feature the above situation can be handled more appropriately.

**Comment by georgweiss** [comment]
Fixed in PR 1289
