### ISSUE TITLE
LED font color doesn't display correctly

### ISSUE THREAD

**Issue by ihtao127** [ControlSystemStudio/phoebus#1269]
I realy like the feature that the LED font changes the color base on the backgroud color, if the LED color is dark, the font changes to a white color, it is good for the readability.

But if the state labels of the LED are the same, this feature doesn't work anymore.

Please look at _**[the video](https://youtu.be/dzVs8tpLde4)**_.

**Comment by kasemir** [comment]
Indeed, you're correct, it's about the label. When the label doesn't change, the color isn't recomputed. Thanks for figuring that out!
Will fix it soon.

**Comment by kasemir** [comment]
For what it's worth, the labels are meant to help users with color vision issues. So it's somewhat important to have different labels to clearly indicate the state.
Still, the bug when using the same label has been fixed.

**Comment by ihtao127** [comment]
Thank you!
