### ISSUE TITLE
Nice to have in Data browser: min/max/avg/dev info to each trace

### ISSUE THREAD

**Issue by mvimercati** [ControlSystemStudio/phoebus#1323]
Hello,
it would be nice to have for each plot trace some important info such as 
* min value
* max value
* average
* standard deviation 
at least for archived data.
Do you think it is feasable?

**Comment by kasemir** [comment]
If your archive data source provides that information, it's shown.

For the RDB archive data source, you get min/max/average.
As described in the online help, the colored outline reflects the min/max, and the line represents the average:

![optimized](https://user-images.githubusercontent.com/1932421/81976430-84291600-95f6-11ea-922e-3cecbdd2f36c.png)


If the archive data source also has std deviation, that's shown via another thinner line:

![Screen Shot 2020-05-14 at 3 20 35 PM](https://user-images.githubusercontent.com/1932421/81976446-8ab78d80-95f6-11ea-9755-1aaed386e949.png)

**Comment by mvimercati** [comment]
I read about this feature but I understood that it was related to downsampling/binning the retrieved data from archive. What I mean is a simple average all over the selected period, so it would be one number information for all the chart.
Am I missing something?
BTW thanks for you reply

**Comment by kasemir** [comment]
The data browser properties panel has a "Statistics" tab, https://github.com/ControlSystemStudio/phoebus/pull/1532 :

![Screen Shot 2022-03-03 at 8 52 49 AM](https://user-images.githubusercontent.com/1932421/156578282-ee5d5f61-8ca0-4f85-a8f7-b23c554025a7.png)
