### ISSUE TITLE
Macros dialog editing behaviour improvement

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#1324]
Depending on where you click and the number of clicks users quite often find themselves in the situation that multiple clicks had resulted in the <Enter Name> to not only be deselected but the cursor has moved to the end of the default text. After which an edit cancel results in parsing error.

![image](https://user-images.githubusercontent.com/2111304/81853861-0d731680-952b-11ea-9a72-bbc7372036c1.png)

Suggested solution.
When an edit action is started the default text should be removed.

**Comment by kasemir** [comment]
Might be easier to just remove the `Messages.MacrosTable_*Hint`.
Those in the know can still click on the cell to edit.
Those who don't see the "Add" button.
