### ISSUE TITLE
Test and Demo class location and name

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#1329]
The usual convention is to 
1. place unit test and demo classes in a matching package under /src/test as it is under /src/main
2. match the name of the demo or test to the class being tested/demoed.

We do not need to change everything immediately but does everyone agree with this convention so that we can adopt it and modify files when we come across them.

**Comment by kasemir** [comment]
Note additional detail from failed code conventions attempt regarding the naming of tests vs. demo code, https://github.com/ControlSystemStudio/phoebus/pull/1031: 



All test code under `src/test/java` with classes that end in `*UnitTest.java`
 should be such that it can be executed by anybody at any time,
 including automated build systems used for continuous test and integration.

 Test code that requires manual intervention or can only be executed
 within a certain test infrastructure (database, network services, ...)
 should be called  `*Demo.java`.
