### ISSUE TITLE
PV Table Save and Restore flag not restored from .pvs file

### ISSUE THREAD

**Issue by mvimercati** [ControlSystemStudio/phoebus#1397]
This is probably because flag is restored from child:
https://github.com/ControlSystemStudio/phoebus/blob/02f8c6fdc3fd86876b1606e6c0026637a6896d00/app/pvtable/src/main/java/org/phoebus/applications/pvtable/persistence/PVTableXMLPersistence.java#L83

while it is saved as attribute of pvtable:

https://github.com/ControlSystemStudio/phoebus/blob/02f8c6fdc3fd86876b1606e6c0026637a6896d00/app/pvtable/src/main/java/org/phoebus/applications/pvtable/persistence/PVTableXMLPersistence.java#L151

**Comment by kasemir** [comment]
Good catch. I'll leave it as an attribute and fix the load.
