### ISSUE TITLE
duplicate declaration in core-framework

### ISSUE THREAD

**Issue by jeonghanlee** [ControlSystemStudio/phoebus#1401]
@kasemir, @shroffk, @georgweiss  

I would like to know, somehow from the fresh compiling without the exist .m2 directory, I have to remove L27-32 in pom.xml 

* https://github.com/ControlSystemStudio/phoebus/blob/f2ec18bb3fd961ec957a781eba55e7c3a98bf2bb/core/framework/pom.xml#L10-L14
* https://github.com/ControlSystemStudio/phoebus/blob/f2ec18bb3fd961ec957a781eba55e7c3a98bf2bb/core/framework/pom.xml#L27-L32

The error, which I encounter is 
```
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.5.RELEASE/spring-boot-dependencies-2.1.5.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.phoebus:core-formula:jar -> duplicate declaration of version 4.6.4-SNAPSHOT @ org.phoebus:core-framework:[unknown-version], /home/jhlee/gitsrc/phoebus-env/phoebus-src/core/framework/pom.xml, line 27, column 17
[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:2.1.5.RELEASE from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots): proxy: Name or service not known @ org.phoebus:service-alarm-logger:[unknown-version], /home/jhlee/gitsrc/phoebus-env/phoebus-src/services/alarm-logger/pom.xml, line 17, column 19
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter:jar is missing. @ org.phoebus:service-alarm-logger:[unknown-version], /home/jhlee/gitsrc/phoebus-env/phoebus-src/services/alarm-logger/pom.xml, line 29, column 17

```

Please let me know what you think. 

@kasemir , sorry about the maven building dependency issues.

**Comment by shroffk** [comment]
@jeonghanlee good catch,
we can remove the duplicate definition

**Comment by kasemir** [comment]
Do you need to keep the one with or the one without `<scope>compile`?

**Comment by shroffk** [comment]
By default no scope should mean compile...
Looking back this duplicate dependency was declared cause I was having problem getting eclipse to recognize the dependency.
I think I have a previous issue ticket about java error in eclipse when importing phoebus. I have a PR which removes the duplicate

**Comment by shroffk** [comment]
@jeonghanlee this should be resolved now. Thanks for checking out the warnings and helping clean up :)

**Comment by jeonghanlee** [comment]
Thank you!!!
