### ISSUE TITLE
opi "menu" widget with no label (i.e. label is an empty string) is translated to .bob "ActionButton" widget with label "No PV"

### ISSUE THREAD

**Issue by oksanagit** [ControlSystemStudio/phoebus#1410]
Hi,
Please take a look at the attached pic. 
I actually made a fix for it and will create a PR in a few. 

![PhoebusNoPV](https://user-images.githubusercontent.com/21367956/86285873-6ec27800-bbb3-11ea-94fd-5c4eb55ca3d4.jpg)

**Comment by kasemir** [comment]
How do you get that display?
Are you converting from MEDM to *.bob?
Or are you opening a *.opi display (which had previously been converted from MEDM)?

**Comment by oksanagit** [comment]
I am opening an .opi display, which was previously converted from MEDM.  We would like to move to the new product as smooth as possible, and  it is my understanding that same code is being used in both scenarios: opening an .opi screen and translating from .opi to .bob and opening bob. Thank you.

**Comment by kasemir** [comment]
There are 2 routes:

1) MEDM -> *.opi (using the converter in BOY) -> open *.opi in Display Builder
2) MEDM -> *.bob (using the converter in the display builder)

You chose 1), which is fine.
Can you attach the *.opi file?

**Comment by oksanagit** [comment]
[pointGrey.opi.txt](https://github.com/ControlSystemStudio/phoebus/files/4864790/pointGrey.opi.txt)
I had to add .txt. .opi extension was not accepted as legitimate.

**Comment by kasemir** [comment]
Thanks.
Can you add ADPlugins.opi, since that's the one with the actual menu buttons in question:

![Screen Shot 2020-07-02 at 10 58 02 AM](https://user-images.githubusercontent.com/1932421/86374781-f27f7180-bc52-11ea-8ac1-d68d491bb377.png)

**Comment by oksanagit** [comment]
[ADPlugins.opi.txt](https://github.com/ControlSystemStudio/phoebus/files/4865580/ADPlugins.opi.txt)
Yes, sorry, this is an included display, the main part of the story.

**Comment by oksanagit** [comment]
Let me know it anything else is needed. Thanks

**Comment by kasemir** [comment]
OK thanks, will look at it.

**Comment by kasemir** [comment]
Try with the latest. Thanks for finding this.

**Comment by oksanagit** [comment]
I have tested the master branch, looks good to me. Thank you Kay!
