### ISSUE TITLE
ModelResourceUtilTest fails on Windows

### ISSUE THREAD

**Issue by domensoklic** [ControlSystemStudio/phoebus#1419]
When building on Windows, the following test fails:
`[ERROR]   ModelResourceUtilTest.testExamples:49 » InvalidPath Illegal char <:> at index ...`

On Linux the test passes.

**Comment by shroffk** [comment]
I cannot reproduce this error.
Both within the IDE and via command line maven build this test passes on windows

**Comment by kasemir** [comment]
This might be outdated,  the ModelResourceUtil has been updated since.
