### ISSUE TITLE
Reading from waveform PV only returns the first element

### ISSUE THREAD

**Issue by krisztianloki** [ControlSystemStudio/phoebus#1461]
Using a waveform PV as a string and trying to display it in a Text Update will only show the first character. It is the same with the probe tool; changing the format does not help. It works with 4.6.3 though

**Comment by kasemir** [comment]
What's the data type? Must be a CHAR waveform.

**Comment by kasemir** [comment]
Example: PV is a char waveform, plain probe shows the characters, but with Format: String you get the chars as a string.

<img width="1299" alt="Screen Shot 2020-08-07 at 1 05 23 PM" src="https://user-images.githubusercontent.com/1932421/89670176-bf15af80-d8ae-11ea-8be9-06798108b40f.png">

**Comment by krisztianloki** [comment]
It is a CHAR. I was able read it in the Eclipse based CS-Studio and Phoebus-4.6.3 but not with the development version.
But when I tried again just now I can... I don't quite understand... I'll try to reproduce it next week...

**Comment by krisztianloki** [comment]
So this is what I did:
 - set the waveform to `foobar` using the latest Phoebus
 - the Text Entry changed from `foobar` to just `f`
 - confirmed that the string was correctly set using both `caget` and `dbgf` in the IOC
 - stopped latest Phoebus and started 4.6.3
 - Phoebus-4.6.3 correctly displayed `foobar`
 - stopped 4.6.3 and started latest Phoebus
 - latest Phoebus now displays `foobar`

**Comment by kasemir** [comment]
> set the waveform to foobar using the latest Phoebus
> the Text Entry changed from foobar to just f

Cannot reproduce. Entering new text works OK with a waveform like this:
```
record(waveform, "text")
{
  field(FTVL, "CHAR")
  field(NELM, "200")
}
```

<img width="363" alt="Screen Shot 2020-08-07 at 1 30 49 PM" src="https://user-images.githubusercontent.com/1932421/89672190-4c0e3800-d8b2-11ea-9b30-06aff987989e.png">

**Comment by krisztianloki** [comment]
It seems to work with a local IOC... maybe it has something to do with the CA gateway? Reloading the OPI also fixes the problem.

**Comment by kasemir** [comment]
There might be a problem with the gateway not handling changing array sizes.
We also never use a gateway with write access, ours are all read-only, so cannot check.

**Comment by krisztianloki** [comment]
You are right. It was the gateway. `camonitor` also showed the first character only and the array size did not change. Thanks for the help!

**Comment by ralphlange** [comment]
Please file an issue with the Gateway. It handles changing array sizes on monitor connections, and should handle this case.
https://github.com/epics-extensions/ca-gateway/issues
