### ISSUE TITLE
Should localizations be upstreamed?

### ISSUE THREAD

**Issue by tmijail** [ControlSystemStudio/phoebus#1477]
Hello,

I'm working on translating Phoebus to Spanish. 
I see that there are a few `messages_de.properties` files in the repo, but not much in the way of a full translation; so I was wondering whether I should make a PR here once my work is done, or if I should just treat it as a site customization and keep it in my own repository.

Thanks for your time.

**Comment by georgweiss** [comment]
I think you should create a PR. I have Spanish speaking users that might appreciate this.
