### ISSUE TITLE
Python + scriptinfo

### ISSUE THREAD

**Issue by SBonneau1985** [ControlSystemStudio/phoebus#1550]
Hello,
I’m looking for how to configure a scripts property of a widget from python code.
In the case of reading with widget.getPropertyValue("scripts) the result is:
[ScriptInfo('../Scripts/Main/RulesSaf.py', [PV '$(pv_name):StateMbb.B0', PV '$(pv_name)'])]
 
For writing widget.setPropertyValue("scripts", rules) but I don’t know how to define "rules"

S.Bonneau
Ganil/ G2CA

**Comment by kasemir** [comment]
Rules can be configured in the display editor. At runtime, the addition of rules from within a script is not supported.
