### ISSUE TITLE
Widget selection with SHIFT key down 

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1594]
In edit mode, when user selects a widget in the "outline" list and subsequently presses arrow up/down while SHIFT key is pressed, the widget below/above is also selected. However, if user with SHIFT key down presses arrow up/down again, the editor starts to resize the selected widgets. The expected behavior would be to select next widget in the list.

**Comment by krisztianloki** [comment]
There are other use cases where the focus is "stolen"; trying to move a widget with the arrow buttons results in changing editor tabs...
