### ISSUE TITLE
Jersey doesn't seem to support Java 9

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/phoebus#160]
See: https://github.com/eclipse-ee4j/jersey/issues/3733

**Comment by shroffk** [comment]
We could also consider using the spring boot rest client itself.

@willrogers I remember you had made a list of possible alternatives.do you remember where they are?

**Comment by willrogers** [comment]
Alternatives to what?

**Comment by shroffk** [comment]
Rest client library (instead of jersey)

________________________________
