### ISSUE TITLE
Channel finder views: Persist 'query', position 

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/phoebus#1620]
When closing and then re-opening Phoebus, the "Channel Tree" and "Channel Table" don't save/restore the "Query: ____" string.
They probably should, just like "Probe" and "PV Tree" persist the current PV name.

When opening "Channel Info" from the context menu, that dialog appears in the center of the primary monitor, even if the Tree/table from which it was opened is on a secondary monitor.
Should use something like `DialogHelper.positionDialog(...)` to make it appear close to the UI from which it was opened.

**Comment by shroffk** [comment]
Ok,

+1 on persistence

I think the channelInfo was just a quick port from the old cs-studio.

+1 for dialog helper

I will add both things.
