### ISSUE TITLE
build java doc error

### ISSUE THREAD

**Issue by forestmojo** [ControlSystemStudio/phoebus#1669]
Followed the steps to build javadoc as:
Build the Javadoc, i.e. html files to be included in the manual
( cd phoebus/app/display/editor; ant -f javadoc.xml clean all )
but there are many errors such as :
error: package org.csstudio.display.builder.model.properties does not exist
error: static import only from classes and interfaces

**Comment by shroffk** [comment]
Can you try the following in the top folder.

```
$ mvn clean verify -DskipTests=true -Psphinx -N
```

**Comment by kasemir** [comment]
Update docs/README.md to show `mvn clean verify ..-Psphinx` instead of example without `clean`?

**Comment by shroffk** [comment]
copy pasted the clean but like you point out... it is not needed

**Comment by forestmojo** [comment]
hi, shroffk:

Another question about olog, on https://olog-es.readthedocs.io/en/latest/, it says “ Detailed Installation Instructions: Install Olog-es.” , but the link is broken.  Would you please correct this?
Or does phoebus support elog now?

> 
> 
> Can you try the following in the top folder.
> 
> ```
> $ mvn clean verify -DskipTests=true -Psphinx -N
> ```

**Comment by shroffk** [comment]
@forestmojo thanks for this catch
Fixed the link 
https://github.com/Olog/olog-es/commit/4dec6030c5d3ea0f6a48f5aa03bf93e26f548288

Can we close this issue
