### ISSUE TITLE
Controls.fx version update

### ISSUE THREAD

**Issue by pavel-ch** [ControlSystemStudio/phoebus#1690]
Can we use latest controls.fx maintained version 11.0.3 instead of 9.0.0 version? As I can see it is used in org.csstudio.display.builder.representation.javafx.widgets.SlideButtonRepresentation. I use it in a site specific code and want to be up to date. Thanks for hints.

**Comment by kasemir** [comment]
I don't see a problem with updating, go ahead and make a PR, especially if you have (site specific) code that can tell the difference between "too old" and "good now".

**Comment by kasemir** [comment]
Done, now have controls.fx 11.0.3.
