### ISSUE TITLE
Question: adding ESS specific tags

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1709]
In order to be able to maintain Phoebus releases internal to ESS without impacting common pom files, we would like to add tags every now and then. These would be of the format ESS_x.y.z where x.y.z is a version number maintained by us.

Any objections?

**Comment by shroffk** [comment]
I would be ok with this so long as we don't have hundred of tags.
A few tags to mark important commit should be fine.
