### ISSUE TITLE
Preference view

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#1711]
With multiple beamline and multiple sets of preferences becoming quite common at NSLS2 a simple UI would be quite useful.
The current goal is to work on a read only view.

**Comment by shroffk** [comment]
![image](https://user-images.githubusercontent.com/2111304/102809840-b2db4c00-4390-11eb-9cf9-3fa7a19a9b1e.png)

**Comment by krisztianloki** [comment]
A future feature could be to make the individual preferences available as PVs so a "Preferences UI" could be created with Display Builder itself

**Comment by kasemir** [comment]
Note that you can also view the preferences, in a format that you can copy/paste into your own settings.ini file, via Help, About, Show Details, Preference Settings

**Comment by georgweiss** [comment]
Any plans to merge this?
Asking as we are rolling out distribution of Phoebus from IT management tools. Users would then need a convenient way to edit preference settings as command line will not point to an ini file.

**Comment by shroffk** [comment]
This is merged. You will have to include this in the site specific product

**Comment by georgweiss** [comment]
OK.
Any plans to support simple edit (i.e. restart required)?
