### ISSUE TITLE
VTypeHelper add support for boolean

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#1720]
I would like to expand the VTypeHelper to add method to create VBoolean's

```
.toVBoolean(VType)
```

If the argument is string then it parses "true" and "false" 
If the argument is a number then 1 is parsed as true and all other numeric values are parsed as false

@kasemir @georgweiss 
Is this ok? am I missing some other cases

**Comment by georgweiss** [comment]
In C zero is interpreted as false, all other values as true, if memory serves me right.

**Comment by kasemir** [comment]
Yes, zero is false, any non-zero value should be true to be compatible with C, python, ...
