### ISSUE TITLE
Alarm Config Logger does not handle comma separated topics

### ISSUE THREAD

**Issue by jacquelinegarrahan** [ControlSystemStudio/phoebus#1730]
A comma separated list of topics passed via the -topics argument is treated as a single topic:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/25035114/104380236-8f16ac00-54df-11eb-8e69-09d04a369688.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/25035114/104380250-92aa3300-54df-11eb-8971-563b5a84e7e6.png">

**Comment by georgweiss** [comment]
This is indeed a bug as the alarm config logger uses colon (:) as separator.
Will fix this.

**Comment by georgweiss** [comment]
Fix in PR #1732.
Can we close this?

**Comment by shroffk** [comment]
@jacquelinegarrahan can this be closed it looks like the fix has been merged

**Comment by jacquelinegarrahan** [comment]
@shroffk sorry for the delay
