### ISSUE TITLE
add specific widget 

### ISSUE THREAD

**Issue by CC-g2ca** [ControlSystemStudio/phoebus#1745]
Hi, we are finished working on our widget and we would like to separate our development and all community development.

can you give us a solution or docs to help us !

Thank you in advance...

**Comment by kasemir** [comment]
You best create a repository for your site, see https://github.com/ControlSystemStudio/phoebus/tree/master/phoebus-product.
It could be as small as just a pom.xml or build.xml for assembling a product that includes those standard components that you want to use, where you decide if you want to use the channel finder support or not, if you pick one of the existing logbook bindings etc.
Then you add your site-specific settings.ini to configure the EPICS CA address list, home display etc., and maybe add your own splash image.

So far, that would not require any Java code, but in your case you would then add the code for your site-specific widgets, which (like any widgets) use SPI  (META-INF/services/.. files) to get hooked into the product. 
For an example, see https://github.com/shroffk/nsls2-phoebus  or https://github.com/kasemir/phoebus-sns
