### ISSUE TITLE
dependencies packaging

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#183]
Should the dependencies project be packaged as a jar?
Wouldn't it make more sense as a pom since the goal is to create the lib folder.

**Comment by kasemir** [comment]
Yes, the desired outcome is a lib folder that contains all external dependencies.

Maven happens to create a dependencies-0.0.1-SNAPSHOT.jar which we don't need. If maven can skip that,  and only create the target/lib, that would be fine.

**Comment by shroffk** [comment]
> Maven happens to create a dependencies-0.0.1-SNAPSHOT.jar which we don't need. If maven can skip that, and only create the target/lib, that would be fine.

I think that should be possible.

**Comment by kasemir** [comment]
https://controlssoftware.sns.ornl.gov/css_phoebus offers builds that includes target platforms.
To build without maven, one can download & unzip phoebus-target-linux.zip, phoebus-target-mac.zip,  phoebus-target-win.zip and then build 100% locally with ant.
