### ISSUE TITLE
"Rename item" in alarm tree

### ISSUE THREAD

**Issue by tanviash** [ControlSystemStudio/phoebus#1849]
When a PV in alarm tree is renamed using "rename item" option such that what it is being renamed to is in UNDEFINED/Disconnected state, the original PV gets deleted from the alarm tree but the new PV does not get added to alarm tree. This problem is not seen when original PV is being renamed to a connected PV in which case the original PV gets renamed correctly inside the tree.

**Comment by tanviash** [comment]
Closing this as I haven't seen this since #1850 fix.

**Comment by kasemir** [comment]
Good, thanks for the update
