### ISSUE TITLE
Question: GraphicsUtils.convert(javafx.scene.paint.Color) to honor alpha?

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1854]
In some cases my users wish to set a transparent background on widget, e.g. the Meter. Currently the alpha value is not honored as the the GraphicsUtils.convert(javafx.scene.paint.Color) method ignores the opacity value of javafx.scene.paint.Color. 

Changing the convert method to use the opacity value when converting to java.awt.Color seems to be the simplest change to make opacity work as expected when selecting for instance a widget background color. I have checked with a few site OPIs as well as some of the example OPIs and cannot see any obvious issues.

Question is consequently if there are any reasons to not change in GraphicsUtils.convert(javafx.scene.paint.Color) from:
```
return new java.awt.Color((int) (color.getRed()*255),
                                  (int) (color.getGreen()*255),
                                  (int) (color.getBlue()*255));
```
to

```
return new java.awt.Color((int) (color.getRed()*255),
                                  (int) (color.getGreen()*255),
                                  (int) (color.getBlue()*255),
                                  (int) (color.getOpacity()*255));
```

**Comment by kasemir** [comment]
Should be OK.
