### ISSUE TITLE
Databrowser axis auto scale behavior

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#1937]
Auto rescaling of Y axis seems to be triggered by various changes, e.g. time range change, changing the order of the PVs, refreshing the plot, changing the request type from "Optimized" to "Raw data". Such triggers rescale even if auto_scale=false.

Bug or intended behavior?

Eclipse-based CS Studio does not exhibit the same behavior, so assuming this is a bug...

**Comment by kasemir** [comment]
Do you have https://github.com/ControlSystemStudio/phoebus/blob/3e468cf6b913e2a21ffabbce7b0443147386b1cb/app/databrowser/src/main/resources/databrowser_preferences.properties#L96 set to STAGGER? Those changes you mention result in fetching data, and at the end of fetching data the `archive_rescale` is performed

**Comment by georgweiss** [comment]
Thanks.
