### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by thomasms** [ControlSystemStudio/phoebus#1943]
When trying to view the raw rst file for the documentation, I tried the link circled in red below, but the link seems broken. It is not clear to me where the correct file lies on the repository.

![image](https://user-images.githubusercontent.com/8820266/124119669-15658100-da73-11eb-9f08-c99519ce1aa3.png)

**Comment by kasemir** [comment]
Unfortunately, read-the-docs assumes that all documentation is in one large GitHub repo just for the *.rst files, but we assemble the doc from app-specific sections.
Documentation is in `doc` folders next to the corresponding tool, in this case https://github.com/ControlSystemStudio/phoebus/tree/master/services/alarm-config-logger/doc

For more see https://github.com/ControlSystemStudio/phoebus/tree/master/docs

**Comment by thomasms** [comment]
Fair enough. I made a pull request to fix the small but annoying grammatical error in the documentation, if this helps.
#1944

**Comment by kasemir** [comment]
Thanks

**Comment by thomasms** [comment]
Happy to help.
