### ISSUE TITLE
Copy PV value to clipboard

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/phoebus#1953]
We support copying a PV name to clipboard, from the context menu of widgets.

Add "Copy PV Value to clipboard"?

**Comment by shroffk** [comment]
This would be value, timestamp, alarm, egu.... or just value

In general it think +1

**Comment by kasemir** [comment]
Saw that in the react automation studio demo and wondered if it's useful.
Yes, probably best copy time, stat/sevr, value, units.

**Comment by shroffk** [comment]
Maybe we want to ensure that we do not support this for waveforms...not sure copying the waveform array representing a large image is useful or good for the clipboard
