### ISSUE TITLE
Is There A Mailing List?

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [ControlSystemStudio/phoebus#1982]
I looked at https://docs.google.com/document/d/1lyfA1ZaLIxfFpJ972TTl_2r_n4--V7tJuzLhp53ZOOg/edit#heading=h.7jjdypgltu4f

but couldn't find a mailing list.

Thanks
Lorenzo

**Comment by shroffk** [comment]
We have the mailing lists on the website
https://controlsystemstudio.org/about

Contact
User Level Questions: EPICS Tech-Talk Mailing list

Developer Level Questions: cs-studio-core@lists.sourceforge.net

Report Bugs/Problems: GitHub Issue Tracker

**Comment by lorenzo-gomez-windhover** [comment]
Thanks!
