### ISSUE TITLE
Alarm Server API -- please?

### ISSUE THREAD

**Issue by cogansco** [ControlSystemStudio/phoebus#2042]
I am interested to write some python applications to improve automated management of alarms, which could ultimately be used to create summary EPICS PV that can be displayed on regular CS-Studio screens.

What is the API for the alarm server?  Does one exist in python?

**Comment by kasemir** [comment]
I'm leaning to close this issue. The Kafka messages as documented in https://github.com/ControlSystemStudio/phoebus/blob/master/app/alarm/Readme.md are way to interact with the alarm system. It's what the alarm server uses to communicate the alarm state, it's how the UI displays the current state and allows configuration changes, it's how the alarm logger tracks both configuration and state changes. Kafka is accessible from a variety of programming languages to allow creating additional custom, site-specific alarm clients.
