### ISSUE TITLE
alarm message logging service updates

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#2068]
1. There are fields in the elastic template marked as text with additional mapping to keywords. 
```
"message" : {
            "type" : "text",
            "fields": {
              "keyword": { 
                "type": "keyword"
              }
            }
```
We could update the type directly to "keywords"
@tanviash would this be ok?

2. The statup scripts can be incorporated in the service itself, upon startup if the elastic templates are missing then they are created.

3. The REST api should be expanded so that clients don't have to make direct elastic calls - we will have to update elastic to 7? maybe 8? soon and it might be nice to avoid the situation where we have to update the client every time.

**Comment by tanviash** [comment]
Hi Kunal, yes it is okay to go ahead. Thanks for the update. I'll keep an eye on your changes so I can test it out on our test setup.
