### ISSUE TITLE
Enabled Time in AlarmModelReaderTest

### ISSUE THREAD

**Issue by mgotz** [ControlSystemStudio/phoebus#2081]
Hi,
in the AlarmModelReaderTest the test XML contains an enabled by date, which expired this morning
https://github.com/ControlSystemStudio/phoebus/blob/5ef3329c466f91963215bb5819b474bafeeff87b/app/alarm/model/src/test/java/org/phoebus/applications/alarm/AlarmModelReaderTest.java#L83-L85

this causes this test to fail: 
https://github.com/ControlSystemStudio/phoebus/blob/5ef3329c466f91963215bb5819b474bafeeff87b/app/alarm/model/src/test/java/org/phoebus/applications/alarm/AlarmModelReaderTest.java#L182
It should probably be changed to something further in the future, like 2099.

**Comment by georgweiss** [comment]
Fix is merged.
