### ISSUE TITLE
phoebus.bat fails to find java when first executed

### ISSUE THREAD

**Issue by kurup** [ControlSystemStudio/phoebus#2140]
The phoebus.bat script doesn't assign the JAVA_HOME variable with `ENABLEDELAYEDEXPANSION` set so the variable is not assigned properly when the script is first executed, which means the version of java in `../jdk` is not found. Subsequent execution of the script works. This is fixed when `set ENABLEDELAYEDEXPANSION` is at the top of the script and `%JAVA_HOME%` is replaced with `!JAVA_HOME!`

**Comment by kasemir** [comment]
Thanks for the info! Way back, I created that phoebus.bat based on the phoebus.sh without knowing much about the specifics of Windows, which I hardly use. @shroffk or somebody else who actually uses Windows, can you check this?

**Comment by shroffk** [comment]
@kurup thanks... Do you want to open a PR and I can check this and merge it :)

**Comment by kurup** [comment]
@shroffk yes I'll do this.
