### ISSUE TITLE
github actions failing

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#2180]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project parent: Failed to retrieve remote metadata org.phoebus:parent:4.6.6-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.phoebus:parent:4.6.6-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/ControlSystemStudio/phoebus): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
```

**Comment by shroffk** [comment]
@lorenzo-gomez-windhover can you look into this

**Comment by shroffk** [comment]
@lorenzo-gomez-windhover I believe `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` is not available in the docker container on which the tests are being run
We will have to find a way to make this available for the publish step to work

**Comment by lorenzo-gomez-windhover** [comment]
Yes, I missed that! There is a way of doing it. I will get on it as soon as possible.

**Comment by shroffk** [comment]
It doesn't seem to have worked with the above fix :(

**Comment by lorenzo-gomez-windhover** [comment]
Yes, we should. Sorry about this guys. I'll be making a PR shortly to go back to CI without containers. I'll keep looking into these issues further in the future.

**Comment by andersharrisson-ess** [comment]
Sorry, I've been swamped with other work and haven't been able to help out on this issue. Reverting the change was reasonable.
