### ISSUE TITLE
Spinner widget focus behavior

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2181]
In the TextEntry widget the value is selected when it acquires focus. This in turn will cause any keyboard input to overwrite the current value. In the Spinner widget on the other hand the value is not selected so anything typed from the keyboard will instead be inserted.

The difference in behavior has caused some users to commit wrong values from the Spinner widget as they assumed it to behave in the same manner as the TextEntry widget.

Question is if the Spinner widget should be changed. I guess numerous users are fine with how the Spinner works, so a change could cause confusion and frustration.

**Comment by kasemir** [comment]
I'm in favor of updating the spinner widget's text section to be like the text entry (or table cell): Select all on focus, typing will replace what's there (or use escape to cancel, cursor keys to only edit some part of it)

**Comment by kasemir** [comment]
Another inconsitency: Open example, incremental controls, click or tab into the spinner, type "error".
Tab out, or click elsewhere, or type "Escape": The spinner continues to show "error".
"Escape" should certainly abort any change and restore the current value.
Unclear it otherwise losing focus should "commit" the value, in this case fail, and we get the original value back, or if losing focus without "enter" should be just like Escape.

**Comment by georgweiss** [comment]
TextEntry does not commit on Escape, so the Spinner should not either. Feels kind of counterintuitive to commit value on Escape...
I can consider this inconsistency in the same fix.

Any objections to proceed? @shroffk ?

**Comment by kasemir** [comment]
Absolutely, Escape should never commit but abort & restore the current value.
Losing focus without "Enter" is typically just like Escape: Abort, restore current value.
Spinner should also require "Enter" when manually entering a value.
The Up/Down buttons naturally inc/dec and commit, there's no way to "abort" that, and there's also no additional confirmation required.

**Comment by shroffk** [comment]
I am in favour of updating the Spinner to make its text entry behaviour consistent with the TextEntry widget
