### ISSUE TITLE
Progress Bar with Log scale

### ISSUE THREAD

**Issue by tanviash** [ControlSystemStudio/phoebus#2195]
Progress Bars in Phoebus seem not to have the log-scale option that the Eclipse version has. In Phoebus Display Builder, progress bars from legacy OPI seem to display wrong values if the log-scale option is set to true. See the picture (ProgressBarPhoebus.jpg) attached where left column shows the value that progress bar should have indicated. For comparison, see the picture (ProgressBarEclipse.jpg) that shows the same screen with CSS Eclipse.

### Phoebus
![ProgressBarPhoebus](https://user-images.githubusercontent.com/38105093/160170629-9d3c3776-4183-40bd-a48a-903e26e0e8ec.JPG)

### CSS Eclipse
![ProgressBarEclipse](https://user-images.githubusercontent.com/38105093/160170627-4709db4b-3758-4b49-b00f-a6e2d1d1d3fa.JPG)

Progress bar widget is attached below.
[PBWidget.txt](https://github.com/ControlSystemStudio/phoebus/files/8352632/PBWidget.txt)

**Comment by kasemir** [comment]
Try now. It's using the same "log_scale" property name, so should import that from *.boy files.

**Comment by tanviash** [comment]
@kasemir Great, thanks a lot !!
