### ISSUE TITLE
Transparent property for Polygon widgets

### ISSUE THREAD

**Issue by tanviash** [ControlSystemStudio/phoebus#2212]
Support for 'transparent' property for Polygon widgets is missing in Display Builder. Some widgets like rectangle have the transparent property. It is available for polygons in BOY and is utilized for many OPI screens at FRIB.

**Comment by kasemir** [comment]
Could those displays be updated to use poly-line instead of poly-gon?
That should work in both tools.

**Comment by tanviash** [comment]
Hello Kay. Yes, it is possible to use poly-line but it's quite some work to update old OPIs since there are many such instances. Also, we have other area widgets like arc, rectangle, ellipse that do support transparent feature in display builder but polygon also being an area widget is an outlier in this matter.

**Comment by kasemir** [comment]
I'm not too happy with having a "transparent polygon" that's basically a poly-line, but then a rectangle with rounder corners can turn into an ellipse, and a rectangle with height == 1 turns into a (two-point poly-)line. So there is already some overlap between them and considering the overall state of the world these days adding a "transparent polygon" is probably acceptable.
