### ISSUE TITLE
Save restore UI patches

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#2214]
Some minor updated of the ui layouts would make the snapshot viewer and save restore config view better

![image](https://user-images.githubusercontent.com/2111304/163030602-dd47dbff-c110-4741-bc56-ddf68bad0d47.png)

**Comment by shroffk** [comment]
![image](https://user-images.githubusercontent.com/2111304/163030853-1f5d27a7-bf1e-4f95-9450-ec1f5f6a891d.png)

**Comment by georgweiss** [comment]
Agree, looks bad. Will look into it.

**Comment by georgweiss** [comment]
@shroffk, can we close this?
