### ISSUE TITLE
Legacy Linking Container Border 

### ISSUE THREAD

**Issue by tanviash** [ControlSystemStudio/phoebus#2220]
I have a BOY linking container with an OPI file that contains couple of label widgets with borders (see below).

![LinkingContainerBOY](https://user-images.githubusercontent.com/38105093/163622551-46e0de47-9caa-409b-8375-89b5cb9ec0a3.JPG)

When this linking container widget is open in Display Builder as Embedded Display widget, the borders of the labels of the embedded OPI are hidden/cut off like in the picture below.

![EmbeddedDisplayDB](https://user-images.githubusercontent.com/38105093/163622732-084c5a43-5c97-461b-8934-f0cfb9e15150.JPG)

Also, the border color of label changed from pink to orange at runtime.

**Comment by kasemir** [comment]
The screenshot doesn't tell me much. Do you have an example file (main and embedded)?
