### ISSUE TITLE
Tolerances saved in the *.pvs file are ignored in the PV Table application

### ISSUE THREAD

**Issue by konrad-gajewski** [ControlSystemStudio/phoebus#2260]
The tolerances saved in the *.pvs file is overwritten by the default tolerance. It's possible to change it from the context menu and save it to the file but after reloading the file it's again ignored and the default value is used for comparison.
Tested with phoebus nightly build "master 2022-05-09 19:51"

**Comment by kasemir** [comment]
Indeed. I'll look into it.
