### ISSUE TITLE
Scale, minor ticks and markers with ProgressBar widget

### ISSUE THREAD

**Issue by baham4s** [ControlSystemStudio/phoebus#2275]
Hello,

I have on CSS (\*.opi file) a ProgressBar with scale, minor ticks and markers.
![CSSProgressBar](https://user-images.githubusercontent.com/61794844/170230967-25cdbbda-77ce-40d7-8496-2a333567b3b8.png)
But i can't find any way to implement this with Phoebus (*.bob file).
![PhoebusProgressBar](https://user-images.githubusercontent.com/61794844/170231888-5f5c3e41-ce91-4c0d-b7e2-8ca6c119e2e6.png)
Will these properties be implemented in Phoebus?

**Comment by kasemir** [comment]
Closing with #2362
