### ISSUE TITLE
setPropertyValue min max scale on plots doesn't works

### ISSUE THREAD

**Issue by baham4s** [ControlSystemStudio/phoebus#2294]
Hello,

After enabling the "autoscale" property on my y axis, I want to put the original scale back on that same axis but when I use the setPropertyValue on y_axes[n].minimum or y_axes[n].maximum there is no modification of the scale on the plot despite the values being correct.

Test files are attached below.

[bugPropertyPlot.zip](https://github.com/ControlSystemStudio/phoebus/files/8890901/bugPropertyPlot.zip)

**Comment by kasemir** [comment]
> After enabling the "autoscale" property on my y axis

autoscale overrides the min/max.

Disable autoscale, and then a script like this can set the axis limit:
```
from org.csstudio.display.builder.runtime.script import PVUtil
pv0 = PVUtil.getDouble(pvs[0])
widget.setPropertyValue('y_axes[0].maximum', pv0)
```

**Comment by kasemir** [comment]
have you tried turning autoscale off??

**Comment by baham4s** [comment]
Hello,

I've tried your way, but it doesn't work, after autoscale is set to false 
`widget.setPropertyValue("y_axes[0].maximum", pv0)` 
has no action. 
I'm able to set back value who was set before autoscale by updating value inside pv 
`pvs[0].write(scaleMax)`
