### ISSUE TITLE
app-alarm-ui Automated Actions Gui enhancement suggestion

### ISSUE THREAD

**Issue by katysaintin** [ControlSystemStudio/phoebus#2335]
app-alarm-ui Automated Actions Gui enhancement suggestion

By replacing simple Textfield detail column by 2 columns :
- A combobox to select email or cmd
- A textfield to define the information (email or command)

The detail property will built as following option:info 
See the following screenshot to see the difference
![AutomateActionsSuggestion](https://user-images.githubusercontent.com/23193555/180462402-1eeefe7a-6050-4c7a-8520-8f80de2bf44d.png)

I will push my code modification on my Fork https://github.com/katysaintin/phoebus

**Comment by kasemir** [comment]
Since you already support `mailto:` and `cmd:`, can you also support `sevrpv:`?
See https://github.com/ControlSystemStudio/phoebus/blob/master/app/alarm/ui/doc/index.rst

**Comment by katysaintin** [comment]
> Since you already support `mailto:` and `cmd:`, can you also support `sevrpv:`? See https://github.com/ControlSystemStudio/phoebus/blob/master/app/alarm/ui/doc/index.rst

I miss this one, Ok I will add to my suggestion.

**Comment by katysaintin** [comment]
I have just add it (I use a combobox on enumeration)
![AutomateActionsSuggestion](https://user-images.githubusercontent.com/23193555/180465512-11aa44f0-71e2-4476-b0e0-1d2bddbc0993.png)

**Comment by katysaintin** [comment]
There is only a modification in one classe in app-alarm-ui . Do you think I can propose my modifcation as a pull request ?
https://github.com/katysaintin/phoebus/blob/master/app/alarm/ui/src/main/java/org/phoebus/applications/alarm/ui/tree/TitleDetailDelayTable.java

**Comment by kasemir** [comment]
Yes, go ahead and create a PR

**Comment by kasemir** [comment]
update had been merged
