### ISSUE TITLE
OpenDisplay action side effects on Linux

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2394]
My users have spotted a new behavior when an action opens a display with target "New Window": the new window will be rendered, resized and moved, but unfortunately put behind the window from which the action was invoked. Upon next action the window - as it already is available - is put to front. 

Initial conclusion was that first time the window is not rendered, but this is not the case. It's simply obscured.

Note that this was seen on CentOS7 with xcfe. This behavior is **not** seen on MacOS (Monterrey). Windows not tested.

If I comment out in ```DockStage```:

```
 stage.setAlwaysOnTop(true);
 stage.setAlwaysOnTop(false);
```

I get the wanted/expcted behavior on CentOS7, and I cannot spot any other side effects from commenting these lines.
Seems this was added in commit ecbe7ea7481f65288627abd5f25a8aeff5b510d1.

**Comment by kasemir** [comment]
The somewhat overkill sequence of
```
stage.show();
stage.toFront();
stage.setAlwaysOnTop(true);
stage.setAlwaysOnTop(false);
```

was suggested in https://github.com/ControlSystemStudio/phoebus/pull/2341 as a part of supporting `target=window@1038..` but I think allowing to set the location and size is fundamentally different from popping the window to the front. If the plain `show()` suffices, I say go with that.
