### ISSUE TITLE
Data Browser : Add multiple PVs

### ISSUE THREAD

**Issue by GDH-ISIS** [ControlSystemStudio/phoebus#2419]
To help users add PVs of interest and in editing .plt files, would it be possible to include a way of adding multiple PVs to a Data Browser in one action. This would aid data display/editing and reduce development and operation times.

**Comment by kasemir** [comment]
You can drag/drop multiple PVs in from for example a text editor

**Comment by GDH-ISIS** [comment]
Never knew. Pretty much answers my query. Happy times. Many thanks.
