### ISSUE TITLE
Can't hide "Email" context menu

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/phoebus#2461]
The email configuration allows disabling email support:
```
org.phoebus.email/mailhost=DISABLE
```

The display context menu, however, will still include "Send Email".
When invoked, a call to `EmailPreferences.isEmailSupported()` will notice that it's not supported, and nothing happens, which is confusing. Better would be not showing "Send Email" in the first place, or maybe a dialog "Email is not supported".

**Comment by shroffk** [comment]
makes sense...

In the ContextMenuService, I can add a check for the `isenabled()`
