### ISSUE TITLE
Databrowser "Statistics" indicate wrong "Mean"

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/phoebus#2508]
Local user found a situation where the "Mean" appears to be outside the "Min.." .. "Max Value":

![thumbnail_Screen Shot 2023-01-17 at 11 17 50](https://user-images.githubusercontent.com/1932421/212956763-5f6494df-29c5-46eb-b647-97a4b50a0e47.png)

**Comment by kasemir** [comment]
Hard to read, but the red trace shows Min -0.11..., Max 0.12... with Mean 7.18....

**Comment by georgweiss** [comment]
Could it be that there is an exponent for the mean value?

**Comment by georgweiss** [comment]
Of course we could make the columns wider, I'll look into it.

**Comment by kasemir** [comment]
Yes, "7.18E-2" = 0.07 would be an explanation. Unclear if that instance is still running to verify

**Comment by kasemir** [comment]
User was able to change the column width on that instance, and the Mean was indeed "7.18...E-4".

Yes, having the column widths will the width of the pane would have prevented this misunderstanding, though you'll then still be able to make the window size too small to show all values, so there's no perfect solution.

Anyway, nothing severely wrong here.

**Comment by kasemir** [comment]
Yes, thanks!
