### ISSUE TITLE
save/restore elasticsearch docs

### ISSUE THREAD

**Issue by tynanford** [ControlSystemStudio/phoebus#2547]
https://control-system-studio.readthedocs.io/en/latest/services/save-and-restore/doc/index.html?highlight=save#head

https://github.com/ControlSystemStudio/phoebus/blob/master/services/save-and-restore/doc/index.rst#L606

It looks like some git merge things got placed in the docs for save/restore

**Comment by georgweiss** [comment]
Will take care of this. Thanks for spotting it.

**Comment by tynanford** [comment]
Thanks!

**Comment by tynanford** [comment]
Thanks @georgweiss . Completed via: https://github.com/ControlSystemStudio/phoebus/pull/2548
