### ISSUE TITLE
Save and restore : can't add/delete golden tag

### ISSUE THREAD

**Issue by agaget** [ControlSystemStudio/phoebus#2586]
I've updated my fork to the last commit, and since I'm unable to use the tag:
I just have message "Failed to add tag". Same for the custom tags

![image](https://user-images.githubusercontent.com/25428659/225034623-91e0a2d8-7e49-4d25-b3c8-18b88b07f133.png)

@georgweiss  ?

**Comment by georgweiss** [comment]
Have you updated the service as well?

**Comment by agaget** [comment]
Ok, it was updated by I was still linking the old service. Works way bette now. 
Thanks
