### ISSUE TITLE
Save and Restore : Search Snapshot by Name doesn't work

### ISSUE THREAD

**Issue by agaget** [ControlSystemStudio/phoebus#2598]
When I use the little Icon "snapshot" it list me correctly my snapshots, If I add some text On "Node Name" it shows me the following results:

![image](https://user-images.githubusercontent.com/25428659/225686249-ddfc7bb0-eb87-4baa-85e9-8c837cd7335b.png)

I've tried:
- \* : OK
- \*Tune\* : NOK
- \*DETER\* : NOK
- DETERON_5ua_TBL : NOK
- \*DETERON_5ua_TBL\* : NOK
- TuneList: NOK

@georgweiss

**Comment by georgweiss** [comment]
No result searching for TuneList is expected as ticking the snapshot bo the search will consider only snapshots.

The rest is a quite puzzling. I renamed two of my test snapshots to DETERON_5ua_TBL and got the expected result in all of the cases you list, see screen shot for one example.

If you run Elasticsearch on your local box, could you please browse to:
http://localhost:9200/saveandrestore_tree/_doc/<id>

where <id> is the unique id of the snapshot "DETERON_5ua_TBL". You can copy it by right clicking on the snapshot in the tree view.

![Screenshot 2023-03-17 at 09 09 50](https://user-images.githubusercontent.com/35602960/225852378-abb37e62-a732-470b-b67d-92323beda967.png)

**Comment by agaget** [comment]
I'm not sure to understand what you want, but using elasticvue I got 
```

{
	"_index": "saveandrestore_tree",
	"_type": "_doc",
	"_id": "404f109f-735a-4708-bcde-5baddabf95e0",
	"_version": 1,
	"_seq_no": 37,
	"_primary_term": 1,
	"found": true,
	"_source": {
		"node": {
			"uniqueId": "404f109f-735a-4708-bcde-5baddabf95e0",
			"name": "DETERON_5ua_TBL",
			"description": "e",
			"created": 1677243044935,
			"lastModified": 1677243044935,
			"nodeType": "SNAPSHOT",
			"userName": "agaget"
		}
	}
}
```
I've tried to create a new snapshot "disconnected" (because my IOC is shutdown for now), I got the following index, and this one works, I'm able to search it. I possibly create those nodes with a previous version of the save-restore service
```
{
	"_index": "saveandrestore_tree",
	"_type": "_doc",
	"_id": "345a7df3-609d-4ed9-91f8-989c23a2475b",
	"_version": 1,
	"_seq_no": 58,
	"_primary_term": 7,
	"found": true,
	"_source": {
		"node": {
			"uniqueId": "345a7df3-609d-4ed9-91f8-989c23a2475b",
			"name": "disconnected",
			"description": "test",
			"created": 1679044673156,
			"lastModified": 1679044673157,
			"nodeType": "SNAPSHOT",
			"userName": "agaget"
		}
	}
}
```

**Comment by georgweiss** [comment]
Thanks, this is what I wanted to see. Looks as expected.

Did you configure Elasticsearch in any particular manner? I'm asking since the indexing - and consequently the search results - may be affected by for instance how the Elasticsearch analyzer is configured. I use Elasticsearch out-of-the-box, no analyzer configuration done.

**Comment by agaget** [comment]
Elasticsearch is running on my local computer on Xubuntu, I have installed the packet (can't remember how) and launch the service. My elasticsearch.yml is empty (or full of comment).

But still it's working with new snapshot ..

**Comment by georgweiss** [comment]
Still, we're getting different results.

Can you please test with a snapshot with a name containing the underscore character (_)?

**Comment by agaget** [comment]
Ok the problem seems to be the lower/upper case, it's only working with lower case name. 
![image](https://user-images.githubusercontent.com/25428659/225870271-87722b7f-cd9c-4332-9bf3-ae18f83f55b0.png)

**Comment by georgweiss** [comment]
Also: when did you first run the save&restore service? I'm asking as we did a change in the Elasticsearch mapping for the name field 2022-12-16.

**Comment by agaget** [comment]
I have synced my fork yesterday, pull it and generated around 5pm (french hour). I have restarted the save-restore service to be sure, and from a new terminal to be sure to get the correct instance. 
Still nope

And f irst time I have tried Masar was the 2022-12-14 .... :)
 there is some cache files  used since ?

**Comment by georgweiss** [comment]
See my previous comment. Could be you need to drop indices and build your data again.

**Comment by agaget** [comment]
Ok clearing everything on elasticsearch make it works. Good thing I was only on testing.

**Comment by georgweiss** [comment]
FYI: we did not go live with the updated save&restore service until 2023-01-10. And we have not yet made a release to Maven, but expect to do it soon.
