### ISSUE TITLE
Upgrade to Kafka 2.8 ( or 3.4?)

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#2672]
There have been recent improvements in kafka which improve error handling in streams.
The two changes which might be particularly useful are the improvements in how to handle timeouts and handling streams which enter error state

https://cwiki.apache.org/confluence/display/KAFKA/KIP-572%3A+Improve+timeouts+and+retries+in+Kafka+Streams

https://cwiki.apache.org/confluence/display/KAFKA/KIP-671%3A+Introduce+Kafka+Streams+Specific+Uncaught+Exception+Handler

**Comment by georgweiss** [comment]
Thanks @shroffk.

**Comment by tsgit** [comment]
yes, please update to kafka 3.4

currently cmd logging isn't working properly with phoebus alarm logger and kafka 3.4 
the logger doesn't create the  necessary consumers for both the message and cmd stream groups. it's one or the other

**Comment by smarsching** [comment]
I think this has been addressed with #2953 and should be closed, right?
