### ISSUE TITLE
4.7.2 release

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#2680]
I would like to propose a release of the Phoebus Tools and Services version 4.7.2

 - The main motivation is to get the latest EPICS core release incorporated ( working on that release in parallel ) which includes fixes for DLS and improvements from ESS

 - The incompatible API changes to the save and restore service
 
 FYI: @kasemir @georgweiss @tanviash @tynanford @ralphlange

**Comment by shroffk** [comment]
Now that the EPICS core 7.0.9 release has been complete...  I think we are ready for the corresponding 4.7.2 release.

Is there any objection to doing the release tomorrow 24/05/2023 ?

**Comment by georgweiss** [comment]
No objection.
