### ISSUE TITLE
[Question] units after a calculation

### ISSUE THREAD

**Issue by XavSPM** [ControlSystemStudio/phoebus#2715]
Hello,

I am looking for a solution to my problem.

I am performing calculations with several PVs, which have different units. After these calculations, I would like to be able to change the unit of my result.

For example:

![image](https://github.com/ControlSystemStudio/phoebus/assets/104097021/78da40c1-9874-4253-b426-9e98b2fe76f8)

In this case, the first PV is in mSv/h and the second in µA. The result obtained is therefore in mSv/h/µA.

I wonder if it is possible to specify a specific unit for the calculation.

Example: `=PV1/PV2, unit="mSv/h"`

Alternatively, would it be possible to add an option in the widgets to force the use of a specific unit?

Best regards

**Comment by georgweiss** [comment]
I would consider moving the computation to the IOC and present the result in a separate PV. That way you can define the unit as you please and widget would render it "for free".
