### ISSUE TITLE
Tank widget log scale

### ISSUE THREAD

**Issue by ttratnik** [ControlSystemStudio/phoebus#2726]
Hi,

I am having troubles with the log scale of the tank widget.

It doesn't seem to display correct values based on the minimum and maximum values of the scale.
In the example I am attaching the minimum of the widget is set to 1E-9, the maximum to 1E-4 and
limits from PV is turned off.

Best regards
Tomaž

![Screenshot from 2023-06-27 14-28-40](https://github.com/ControlSystemStudio/phoebus/assets/117644550/05d5635c-5089-4545-b6b7-ff8399789dbc)
![Screenshot from 2023-06-27 14-28-57](https://github.com/ControlSystemStudio/phoebus/assets/117644550/de4794b5-1c6f-4118-af9c-02c52918d245)
![Screenshot from 2023-06-27 14-30-36](https://github.com/ControlSystemStudio/phoebus/assets/117644550/77c97f11-103e-4a94-9411-4a2d115cc903)

**Comment by kasemir** [comment]
@abrahamwolk  at ESS is in the middle of creating new bar/tank/scale type widgets, https://github.com/ControlSystemStudio/phoebus/discussions/2718, and overhauling the log axis support, https://github.com/ControlSystemStudio/phoebus/pull/2719, so maybe this can become part of that?
Or you wait for the linear meter widget and then switch to that?

**Comment by ttratnik** [comment]
I decided that I am going to use the progress bar widget whose log scaling works but doesn't have the option to show the scale on the left side. I will just make the scale myself. Maybe I will switch to a different widget later.
Thank you for the reply

**Comment by georgweiss** [comment]
FYI: #2718 does not resolve this issue.

@abrahamwolk is back from vacation Thu July 6th.

**Comment by abrahamwolk** [comment]
@kasemir wrote:
>@abrahamwolk at ESS is in the middle of creating new bar/tank/scale type widgets, https://github.com/ControlSystemStudio/phoebus/discussions/2718, and overhauling the log axis support, https://github.com/ControlSystemStudio/phoebus/pull/2719, so maybe this can become part of that?
Or you wait for the linear meter widget and then switch to that?

Unfortunately, the work on these two items are unrelated: the changes to the logarithmic scale are not related to the Linear Meter, and the Linear Meter currently does not support a logarithmic scale.

**Comment by mellguth2** [comment]
I have no experience with pull requests or may not be authorized, but I checked the following code change and it provided a sensible behaviour of the tank widget when configured with logarithmic scale.
Maybe it can help with fixing this issue.
```
git diff HEAD~1 HEAD
diff --git a/app/rtplot/src/main/java/org/csstudio/javafx/rtplot/RTTank.java b/app/rtplot/src/main/java/org/csstudio/javafx/rtplot/RTTank.java
index 90577ded8..826546c33 100644
--- a/app/rtplot/src/main/java/org/csstudio/javafx/rtplot/RTTank.java
+++ b/app/rtplot/src/main/java/org/csstudio/javafx/rtplot/RTTank.java
@@ -275,8 +275,19 @@ public class RTTank extends Canvas
             level = plot_bounds.height;
         else if (max == min)
             level = 0;
-        else
-            level = (int) (plot_bounds.height * (current - min) / (max - min) + 0.5);
+        else {
+            if (scale.isLogarithmic()) {
+                if (min <= 0 || max <= 0.0 || current <= 0.0) {
+                    level = 0; // refuse to try any mapping if negatives or zero are involved
+                }
+                else {
+                    level = (int) (plot_bounds.height * Math.log(current/min) / Math.log(max/min));
+                }
+            }
+            else { // linear scale
+                level = (int) (plot_bounds.height * (current - min) / (max - min) + 0.5);
+            }
+        }
 
         final int arc = Math.min(plot_bounds.width, plot_bounds.height) / 10;
         gc.setPaint(new GradientPaint(plot_bounds.x, 0, empty, plot_bounds.x+plot_bounds.width/2, 0, empty_shadow, true));

```

**Comment by kasemir** [comment]
@mellguth2 thanks for your suggestion, works fine and has been incorporated only a few months later...
