### ISSUE TITLE
Change color title of group container widget independently

### ISSUE THREAD

**Issue by Mathis-Hu** [ControlSystemStudio/phoebus#2743]
It would be practical to add the possibility of changing the title color of a group container independently of the background color and the color of the line/title bar, because sometimes for the title bar style, the title label is barely visible and we do not want to change all the background or bar color. I did a first version in the code, but I'm creating an issue first rather than creating a pull request to ask if the design is ok with the rest of phoebus.
Before :
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/25616b23-a03b-4a8a-b086-1b3ca4da34f6)
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/25991794-44db-4e55-997d-cef3f372b0dd)

After :
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/ee3b2048-38d9-492c-a06d-7cd02828bab0)
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/81b9d450-e555-4994-a60e-89655238c72f)

Actually, foreground property is for the line and bar color (and label if the style is not TITLE) and background is for the background color (and label if style is TITLE)
In my modification, I looked how it's done with other widget and I'm doing foreground for label (no matter the style), line color property for lines & bar color, and background is still for background color.
To do the conversion with older view version, I had increase the GroupWidget version from 2.0.0 to 3.0.0.

Of course, if this update is implemented to Phoebus, I'll try adding it into DBWR also

**Comment by Mathis-Hu** [comment]
@shroffk

**Comment by mcnanneyd** [comment]
It looks like this commit is what is breaking our BOY to Phoebus conversions. I really like the addition of an independent color title. However, it does seems to break almost all of our screens during conversion. Here is the opi screen before conversion:
![image](https://github.com/ControlSystemStudio/phoebus/assets/91760294/f785eba9-c54a-44f1-af7e-a372652d9e6e)
And its attributes:
![image](https://github.com/ControlSystemStudio/phoebus/assets/91760294/81a78d08-e69e-4ecb-85e2-ce2772f6ed74)

After converting to bob, the screen looks as follows:
![image](https://github.com/ControlSystemStudio/phoebus/assets/91760294/84258317-7ace-4d8c-b921-97ea1ca3ac25)
And its attributes:
![image](https://github.com/ControlSystemStudio/phoebus/assets/91760294/8ba90149-d198-42de-8e2f-8fe291f5d5e8)

So, the border color should be mapped to line color, but it seems to be completely ignored. Is there a way to implement the conversion to meet all of our needs? Thanks!

**Comment by kasemir** [comment]
This was somewhat expected, see comment in PR:
"It's possible that this conversion needs to be tweaked as we open a bunch of older displays and find that we missed something, but that would then be a follow-up update."

So now it's time for such a follow-up ;-)

**Comment by Mathis-Hu** [comment]
I'm on it

**Comment by Mathis-Hu** [comment]
Ok, I'd maked the changes, I'll make a PR.
When merged, you should have the same result as if you had opened it in Phoebus V4.7.2 @mcnanneyd 
Sorry for the inconvenience.

Also, while testing I noticed a difference between Phoebus & CSS (even in 4.7.2), in CSS, it seems that you cannot modify the color title at all and it's light gray (when border style is title bar), same for the line in group box style, it's taking a default darker color based on the background color. While in Phoebus, all colors depends on user choices, so you may have some difference in the conversion.
Is this behavior desirable ? @kasemir

**Comment by kasemir** [comment]
> may have some difference in the conversion...  Is this behavior desirable?

Good question. I would prefer for the only group style options to be "Group Box" and "None", with color fixed to black. Very little to configure, all displays look consistent, and the conversion to the next display tool will be easier. But it's too late, we have the "Title" and "Line" options plus now all colors are configurable, so if somebody doesn't like the color, they can change it to whatever the next person won't like.

For the conversion from other display tools, first let's remember that BOY, the display builder, the web runtime are 3 quite different tools, with completely different graphics libraries.  The fact that you can simply open an older display file and it mostly works is already an accomplishment.

If you can tweak the conversion based on the version numbers, and have logic like "if older version, line_color = background_color.darken()", that's great. Maybe handle that as issues arise, just as you did in this case.

**Comment by mcnanneyd** [comment]
> 

@Mathis-Hu , this is a nice feature that I am glad we have now. Thanks for the quick fix!

**Comment by Mathis-Hu** [comment]
You're welcome, don't hesitate to report other issue if you find some :)
