### ISSUE TITLE
Choice widget behavior

### ISSUE THREAD

**Issue by nusaqib** [ControlSystemStudio/phoebus#2747]
I recently built the Phoebus 4.7.3 and noticed that choice button abnormal behavior in terms of layout. The last item is in opposite orientation to the selected orientation (horizontal/vertical) as seen in the attached screenshots.
![1](https://github.com/ControlSystemStudio/phoebus/assets/76417823/f7c46515-ab5d-442e-8be1-2d43ee05f2d2)
![2](https://github.com/ControlSystemStudio/phoebus/assets/76417823/13cd1185-5d90-4820-9f64-8080eb0d72a7)

**Comment by kasemir** [comment]
Haven't seen that. Looks OK for me:

![Screenshot 2023-07-25 at 4 15 08 PM](https://github.com/ControlSystemStudio/phoebus/assets/1932421/3a3da597-b08c-4983-a44a-6956a7927232)

**Comment by nusaqib** [comment]
Okay, so this was strange. I was noticing same behavior on Rocky 9 and Debian 12 but both had MATE desktop environment. I switched to GNOME and now it's working as expected.

**Comment by kasemir** [comment]
In your screenshot, I'm not sure the horiz and vert alignment is as desired, either.
XFCE seems to work OK, but not sure how the different desktops influence this.
For what it's worth, on Linux, the javafx graphics are based on GTK. For the time being you can select either GTK2 or GTK3, see https://github.com/ControlSystemStudio/phoebus/wiki/Graphics-Performance. Maybe that makes a difference?

**Comment by nusaqib** [comment]
Thanks Kay! Running with GTK2 on MATE resolved this.

**Comment by kasemir** [comment]
Well, good that it works with GTK2. Unfortunately, the 'current' GTK version is 4. GTK2 support in JavaFX has been deprecated a little while ago. Not sure when it will be fully removed.

https://github.com/openjdk/jfx/blob/jfx20/doc-files/release-notes-18.md#deprecate-javafx-gtk-2-library-for-removal

https://bugs.openjdk.org/browse/JDK-8273089
