### ISSUE TITLE
build error: fail during SVGTranscoderTest

### ISSUE THREAD

**Issue by caraxlr** [ControlSystemStudio/phoebus#2764]
Hi, I got some error when trying to run mvn clean install. mvn -DskipTests  clean install -e can work fine. here is the error shown:

```
[INFO] Running org.phoebus.ui.javafx.svg.SVGTranscoderTest
(java:460464): GLib-GObject-CRITICAL **: 13:37:28.960: cannot register existing type 'GSettings'
(java:460464): GLib-GObject-CRITICAL **: 13:37:28.960: cannot add private field to invalid (non-instantiatable) type '<invalid>'
(java:460464): GLib-CRITICAL **: 13:37:28.960: g_once_init_leave: assertion 'result != 0' failed
(java:460464): GLib-GObject-CRITICAL **: 13:37:28.960: g_object_new_valist: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

Thanks for your help!

**Comment by kasemir** [comment]
UpdateThrottleTest completes, note `Tests run: 1, Failures: 0, Errors: 0`.

What fails is SVGTranscoderTest.

**Comment by caraxlr** [comment]
edited, thanks!

**Comment by kasemir** [comment]
Of course no idea why it fails. Georg might have an idea, @georgweiss 
Maybe tell us if this is on Linux, Windows, ..., real computer or a VM without graphics ...

**Comment by kasemir** [comment]
GLib sounds like Linux...

**Comment by caraxlr** [comment]
It's Linux, RHEL 8.8

**Comment by georgweiss** [comment]
Unfortunately I have no way to test on RHEL 8.8. 

Here is a list of things you could try (in this order):

1. Run the build with GTK2, e.g. ```mvn -DjvmArgs="-Djdk.gtk.version=2" install```
2. Build using JDK17 or later
3. Update javafx version in top level pom.xml from 19 to 20 (requires JDK17).

**Comment by georgweiss** [comment]
To me this is a new type of error. Would you be able to determine in which of my suggested steps this error was first shown?

The libawt_xawt.so shared library is part of the Java runtime, see screen shot below taken from a Java 11 installation. The path shown in your error seems a bit odd. Does the folder /home/phoebus3/XIAOL/anaconda3/envs/phoebus17/lib/jvm/lib even exist? If so, what does it contain?

I would maybe download an OpenJDK package (from https://adoptium.net/temurin/releases/) and unzip. Then update your JAVA_HOME environment variable to point to that JDK and try to rebuild.

![Screenshot 2023-08-15 at 8 08 00 PM](https://github.com/ControlSystemStudio/phoebus/assets/35602960/6b535952-35ef-4fda-a2f7-6c018142ce26)

**Comment by caraxlr** [comment]
Hi Georg,

Here is the screenshot of 
/home/phoebus3/XIAOL/anaconda3/envs/phoebus17/lib/jvm/lib

![image](https://github.com/ControlSystemStudio/phoebus/assets/66943769/81d5226d-8228-4c98-9410-f50e0c93ac6d)

It's true that there is no libawt_xawt.so file there. The error was shown when I tried using JDK17.

After I changed to the openJDK package listed in the given website, the build was successful. Thanks!
