### ISSUE TITLE
Epics Archiver Appliance / Save Restore Interoperability

### ISSUE THREAD

**Issue by jembishop** [ControlSystemStudio/phoebus#2781]
Hello, we were wondering if there is any existing (or on the roadmap feature) for integrating the save/restore service with the epics archiver appliance. I can't find anything in the save-restore [documentation](https://control-system-studio.readthedocs.io/en/latest/services/save-and-restore/doc/index.html#:~:text=The%20save%2Dand%2Drestore%20service,restore%20PV%20values%20from%20snapshots) or the epics archiver [documentation](https://slacmshankar.github.io/epicsarchiver_docs/userguide.html).  However it looks like the functionality is almost there given the archiver has an endpoint setup exactly for that purpose. 

The solution we are building in the meantime is a python script which grabs a snapshot from the archiver and uploads the it via the save-restore api.

**Comment by georgweiss** [comment]
Thanks for the question.

While there seems to be an overlap between the archiver appliance and save&restore, I'd claim that there is a subtle but crucial difference. 

The archiver stores values based on monitor events and also based on various settings. Save&restore performs a forced read operation to collect data. Moreover, archived data for a point in time may be an averaged value (e.g. from log term storage). We do currently not plan to integrate save&restore with the archiver appliance.

Populating save&restore storage from archiver to me looks like creating a different type of view of the archiver data.

**Comment by georgweiss** [comment]
Reopening as similar requirements have emerged at ESS.

However, we still insist that archiver data is not of the same "quality" as PV values obtained when explicitly requesting a snapshot. Users should be aware of this and understand that archiver values may in fact be averaged.

That said, a *potential* solution would be to support taking a "snapshot from archiver". This action would launch a date/time picker for user to define wanted point in time for archiver data. Checks would probably have to be performed, i.e. disallow the action if any of the PVs in the configuration are missing from archiver for the selected point in time.

**Comment by jembishop** [comment]
I imagine that all explicitly set user pvs will change at such a slow rate that it should be able to store all the data without any lossy compression. I know you can configure the storage policy in the epics archiver appliance. If you want I could give a go at implementing this feature?

**Comment by georgweiss** [comment]
Sure, why not. However, I'd like us to put down some details here first.
I'll get back as soon as possible. Would like @shroffk to agree on how this should work.

**Comment by georgweiss** [comment]
@jembishop, did you just retract your offer to "give this a go"?

**Comment by jembishop** [comment]
Sorry Georg, I was being a bit hasty there when I said that. Sorry for the confusion! 
The thing is, I've recently created a web app, which is a completely revamped version of the demo I previously shared. It offers the same functionality for saving and restoring, but I believe it's presented in a more intuitive manner. I'll be posting a video of it later today, but the core functionality is:

- Node based hierarchy for storage of configurations
- Ability to look up arbitrary timestamp and compare the values in a table
- Live updating of PV values
- Highlighting between historic and current differences
- Ability to "favourite" a timestamp, and look up favourites
- Ability to ad hoc disable PVs, to restore

The user flow is a bit simpler here. They just look up the timestamp (or favourite), and it fetches the historic values. After inspection they can restore. 

Once you see the video, you can evaluate if it would suit your use case.

**Comment by jembishop** [comment]
https://github.com/ControlSystemStudio/phoebus/assets/40360024/cc9d53af-4fd9-469c-98cd-d58126fb30d3

This is a demo of the app, it is not fully ready but I expect within the next week it will be ready for first release. 

This has a nice interface to organize and edit configurations, and allows you to easily look up archived values and restore to that point. It is a web frontend and uses PVWS so it is easily useable for multiple users.

**Comment by georgweiss** [comment]
This is a bit different compared to our use case. What I had in mind was to let save&restore take a "archiver snapshot" that could optionally be saved like any other snapshot, save for the time stamp and some tag identifying it as based on archiver data. My users' main case is to compare such snapshots to "regular" snapshots.

FYI 1: we are soon releasing a new version that supports role-based access to certain functionality. Authentication/authorization will be optional.

FYI 2: we plan to move creation of snapshots - whether read from IOCs explicitly (as is currently the case) or read from archiver - to the service. The restore operation will also move to the service. These changes are needed to cover a case where the client in Phoebus cannot connect to PVs or cannot write to PVs due to restrictions in the IOC or the network setup.

**Comment by jembishop** [comment]
Ok, I see. In that case I would be happy to contribute some of those features. I could tackle the moving of the PV reading to the service if you want, as it seems that it would be wise to do that first.

I presume we will want to keep the same api endpoint to add a snapshot for backwards compatibility, but there will be another api endpoint say `…/generatesnapshot?parentNodeId=<parent’s node id>`. Then you just pass in a list of the PV names, rather than the `snapshotItems`.

Regarding the snapshot at time functionality this would probably use the same endpoint with a query parameter for the date. For example  `…/generatesnapshot?parentNodeId=<parent’s node id>?at=<timestamp>`. Then in the ui you have an optional datetimepicker with the take snapshot button.

**Comment by jembishop** [comment]
I have raised this issue https://github.com/slacmshankar/epicsarchiverap/issues/189, which if implemented will return VType responses from the save-restore endpoint, which will greatly simplify deserialization. The current pain point is that the archiver appliance will serialize without type context which means you can't deserialize without looking up the type. (For example is "value": 1.0 an integer, float, enum?). 

This additional feature would entail that administrators  would need to update their archiver appliance to the latest version. Do you think that is acceptable in your case?

**Comment by jembishop** [comment]
It seems that the changes proposed by @shroffk will probably improve this interface so I will close this.
