### ISSUE TITLE
Sometimes the horizontal layout for choice buttons are not respected

### ISSUE THREAD

**Issue by Mathis-Hu** [ControlSystemStudio/phoebus#2783]
When I create a choice button, with certain dimension, I the horizontal layout boolean is not respected.
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/3d8a0a07-fe65-4515-ac93-9e8c5f253aae)
And if I put it in Vertical :
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/f7104934-c84f-4da7-ae30-7c8fee11397c)

If vertical, the problem seems to persist independently of the number of items, but if horizontal, it seems to do the problem only on odds number of items (except 2). 
With 3 items
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/57a7d504-12f8-46d1-914c-2f864b4eb2d9)
With 4 items
![image](https://github.com/ControlSystemStudio/phoebus/assets/100083521/a32af5e6-8c46-48de-803e-d0669ab1f52e)

@shroffk

**Comment by kasemir** [comment]
While I cannot dependably reproduce this, I've now seen this happen when moving a display, be it runtime or editor, between monitors.
The layout is right now computed for an exact fit, so in the horizontal case the width of each button is `widget_width / number_of_buttons`. Looks like that layout is too tight, and JFX sometimes decides to spill the last button over into the next row or column.
Will simply make the buttons a little smaller to avoid this.

**Comment by Mathis-Hu** [comment]
Thank you for the change

If this issue is resolved, can I close it ?
