### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jembishop** [ControlSystemStudio/phoebus#2849]
If it is possible could a new release of Phoebus be issued? 
 I would like to have the new version so I can more easily include it as a binary dependency in https://github.com/slacmshankar/epicsarchiverap . I think since Phoebus is a maven project, and the archiver appliance is a gradle project, the option to use a remote github dependency in gradle will not work.  I need the new version as the IPv6 fix which I merged recently in https://github.com/ControlSystemStudio/phoebus/pull/2826 will also fix some issues I have in my build of the epics archiver appliance.
 Thanks.

**Comment by shroffk** [comment]
We are currently working on releasing a few of the dependencies and the middle layer services
I expect next week to release epics core java, channelfinder, phoebus olog, save and restore... following which we should have a new release of Phoebus
Would you be able to wait another 10 days - 2 weeks?

**Comment by jembishop** [comment]
Thanks sounds fine, thanks for getting back to me

**Comment by GDH-ISIS** [comment]
Was wondering whether there was going to be a new release of Phoebus please? I am looking to use the IPV6 fix that was merged recently - mentioned above.

**Comment by shroffk** [comment]
As @georgweiss mentioned... we need to do a new release of epicsCoreJava before a release of Phoebus.
A few of the PR's are also waiting for a release before they can be merged since they change the JDK dependency... we are trying to push forward as quickly as possible on this

**Comment by kasemir** [comment]
>  we need to do a new release of epicsCoreJava

Is this about the already merged update to the VTable serialization https://github.com/epics-base/epicsCoreJava/pull/133, https://github.com/epics-base/epicsCoreJava/pull/134, https://github.com/epics-base/epicsCoreJava/pull/135, only need a release, or are we awaiting more changes?

**Comment by georgweiss** [comment]
Maybe. We've encountered a case where labels array is of different length than the number of values columns. Since column count in IVTable is determined by length of labels/names, the serialized object does not include all data columns.

**Comment by georgweiss** [comment]
Thanks for your understanding.

**Comment by jembishop** [comment]
This is closed given a new release has [happened](https://github.com/ControlSystemStudio/phoebus/releases/tag/v4.7.3)
