### ISSUE TITLE
Shortcut for re-load displays, run displays and middle click for open in new tab

### ISSUE THREAD

**Issue by Mathis-Hu** [ControlSystemStudio/phoebus#2853]
There were several shortcuts in CSS, like :
- Run a Display with F5
- Re-load a Display in editor and in runtime with Ctrl+G

We can also add the possibility of opening a display in a new tab with the middle click onto an action button with open display action (in addition to the shortcut Ctrl + Left Click that already exist for that purpose), it would give another way to do that, just like we can do it in a web browser.

**Comment by kasemir** [comment]
> middle click

Middle-click is somewhat a Linux/X-only idea.
Plus it's already used to copy the PV name, since that's what EDM did.

**Comment by Mathis-Hu** [comment]
> Plus it's already used to copy the PV name, since that's what EDM did.

The middle click is just when clicking on an action button, so it should not be conflictual with EDM, right ?

The goal of that shortcut is when you want to open a large number of displays, it's more fluid with middle click and there's a lot of shortcuts with Ctrl, so the user can use unwanted shortcuts.
