### ISSUE TITLE
Main Phoebus window wants to be on top....mostly

### ISSUE THREAD

**Issue by DuncanAtISIS** [ControlSystemStudio/phoebus#2856]
When opening a dialog (ie from a script, using FileUtil.saveFileDialog) or popped out phoebus display (from an action), the main phoebus window (more often than not) immediately pushes the new window behind itself.

**Comment by DuncanAtISIS** [comment]
Running on MS Windows 10

**Comment by georgweiss** [comment]
Able to reproduce on Windows, but not Mac.
Looks like this is connected to rendering of the tooltip on the action button. Can you please confirm by testing the following:

1. Move mouse pointer away from the button quickly once button is pressed.
2. Set the tooltip of the action button to empty string

**Comment by DuncanAtISIS** [comment]
Thanks for looking at this.  I tried those 2 tests and the results seem to confirm that it's related to tooltip rendering - the popped out display stayed on top.

**Comment by georgweiss** [comment]
OK, thanks for testing. Not sure if this is a JavaFX bug. In any case I'll try to come with a fix.

**Comment by DuncanAtISIS** [comment]
Thanks :)

**Comment by georgweiss** [comment]
Turns out that the behavior described in this ticket is reproducible on Mac OS in a simple JavaFX application. So my suspicion about JavaFX may be incorrect.

**Comment by georgweiss** [comment]
Also tested on Ubuntu (20) with Gnome: behaves like on Mac, i.e. new window is *not* pushed to background when mouse hovers over action button and tooltip is rendered.

**Comment by georgweiss** [comment]
Fixed in #2868
