### ISSUE TITLE
Sort or not alarm items

### ISSUE THREAD

**Issue by lcaouen** [ControlSystemStudio/phoebus#2859]
We would like to have the possibility to keep the order we decided when creating the alarm items and not always sorting them by alphabetical order.
Would be nice to add a parameter "sort_alarm_items" to decide if we want to sort or not the items.

**Comment by kasemir** [comment]
Associated PR has some details as to why it was abandoned. Close this?

**Comment by lcaouen** [comment]
Yes it's abandoned. You can close it.
