### ISSUE TITLE
Reuse AlarmClient instances?

### ISSUE THREAD

**Issue by georgweiss** [ControlSystemStudio/phoebus#2900]
Debugging an issue related to Alarm Table and discovered that a new AlarmClient instance is created whenever Alarm Table, Alarm Tree and Alarm Area Panel are launched, or when user switches to another alarm config.

Seems this could be optimized a bit, i.e. if an application has instantiated an AlarmClient for a configuration, other applications could reuse this. This would save resources in both Phoebus and the Kafka server.

Some kind of manager API would be needed to keep track of instantiated and referenced AlarmClient instances.

Feed-back appreciated.

**Comment by kasemir** [comment]
Yes, in an operational scenario you likely have a few alarm client instances:
Main control room running one each for the area panel, alarm tree, alarm table, annunciator.
Same for additional control stations in the conventional facilities, cryo and target area.
So we get about a dozen alarm clients spread over 4 different hosts.

I have not noticed this as a problem when checking network traffic or profiler logs.
Kafka can handle several thousand additional clients.
We're using the scalability of kafka and keep our side of the code simple:
Each client creates an AlarmClient instance, each instance only needs to track one config and its listeners.
Sure, we could add a layer to pool instances for each config, but at this point I don't see the need.

**Comment by georgweiss** [comment]
Well, the problem I am investigating _could_ be related to Kafka connection issues... But I am not quite done, so I'd like to keep this open.

**Comment by georgweiss** [comment]
Closing this as my issue seems to be related to client connection to Kafka is down.
