### ISSUE TITLE
Grid Step Size min limit in display properties

### ISSUE THREAD

**Issue by Mathis-Hu** [ControlSystemStudio/phoebus#2918]
As I see today, the minimum value of Grid Step Size properties (both horizontal and vertical) in the display is 4.

However in CSS, the limit was 1, so when converting from an opi file, you cannot place new widgets with the same precision, for example in the same line of widgets for LED, so it can be really time consumming to reorder all you widget or to place them with the X Y positions, especially when you have a lot of polygon.

Why is the limit 4 and not 1 ? Can I make a PR to patch this if there's no problem with the min limit of 1 ?

**Comment by kasemir** [comment]
The though was that 1 is the same as turning the grid off, but that really means the smallest usable value would be 2, not 4.
So fine, make it 1.
