### ISSUE TITLE
Alarm tree leaves should show hover information like other PV widgets

### ISSUE THREAD

**Issue by jembishop** [ControlSystemStudio/phoebus#2924]
![image](https://github.com/ControlSystemStudio/phoebus/assets/40360024/4fd16c88-f69d-4ea6-a163-a392f4bc115e)

It would be useful to have relevant hover over information when you mouse over a leaf (or node) of the alarm tree, similar to the usual PV hover view in phoebus.

**Comment by georgweiss** [comment]
The alarm clients consume data only from Kafka, they (intentionally?) do not connect to PVs like widgets do. 

In the context menu of a leaf node user may launch a PV aware view like Probe or Data Browser.

**Comment by jembishop** [comment]
Would it be possible on hover to launch a PV subscription to make this work? I would volunteer to add this feature if you think its a good idea.

**Comment by georgweiss** [comment]
In principle yes, but connection may take a bit of time so rendering data may come with a lag.

I do not mind, but I'd like @shroffk and @kasemir to comment.

**Comment by kasemir** [comment]
Not sure how "on hover to launch a PV subscription" would work.
The tool tip is activated on the UI thread. You must provide the tool tip content right then. If you create the PV at that time, wait for it to connect, then show the text (and of course dispose the PV to avoid leaks), you're blocking the UI thread.
I'm OK with showing whatever information the alarm client has available at the time in alarm UI tool tips, but having the alarm client connect to the live PV sounds wrong. To get to the live PV, you can already open probe etc. from the alarm UI context menu.

**Comment by jembishop** [comment]
Ok fair enough, thanks for your feedback. Looks like this feature might be more trouble than its worth so I will close the issue.
