### ISSUE TITLE
How to change macro value in run time from an action button or click. 

### ISSUE THREAD

**Issue by JordiAnglada** [ControlSystemStudio/phoebus#2964]
Hello all,

I want to change the vale of a macro from an action button, this macro is used to change the PV name on an embedded display (ca://LIPAC-MPS:EV_ST.VAL[$(N1)]).

The idea is by clicking different buttons the macro N1 updates and the embedded display shows different positions of a PV array.

I failed to change the macro value with this action button. There is any way to accomplish that ?

I already tried declaring the macro in a group and anchoring the action button in it (like CS Studio)

![image](https://github.com/ControlSystemStudio/phoebus/assets/80321189/f20f30f3-51a0-4aea-85a4-eb167992081f)

**Comment by kasemir** [comment]
In general, macros are not supposed to change at runtime.

If you want to use an embedded display with a few different macro settings, look at the navigation tabs widget.

If you need to update macros of an embedded display in a more elaborate way, you'll find a script example in the example displays, specifically https://github.com/ControlSystemStudio/phoebus/blob/master/app/display/model/src/main/resources/examples/embedded/update_display.py

**Comment by JordiAnglada** [comment]
Thanks for your response, 

I implemented the script and works fine!
