### ISSUE TITLE
Fix Macro readthedocs

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#3075]
I believe the documentation is incorrect here

https://control-system-studio.readthedocs.io/en/latest/app/display/editor/doc/macros.html#system-macros

The macros **_cannot_** be overwritten by symbol macros

**Comment by shroffk** [comment]
@kasemir I can go ahead and push a fix but wanted your review to verify my understanding

**Comment by kasemir** [comment]
That would be perfect, thanks!
