### ISSUE TITLE
There was an error while compiling the app/display/model in Maven.

### ISSUE THREAD

**Issue by SunamaZero** [ControlSystemStudio/phoebus#3150]
![1](https://github.com/user-attachments/assets/64993104-48fe-41fb-85b4-c34037925a70)

[ERROR]   AdvancedConverterTest.listScriptFilesTest:37 expected: <true> but was: <false>

It seems that there is an error in the "listScriptFilesTest" method of the "AdvancedConverterTest" class regarding the assertion "assertTrue(listScriptFiles.size() == 4)".

**Comment by SunamaZero** [comment]
[ERROR]   AdvancedConverterTest.listScriptFilesTest:37 expected: <true> but was: <false>

**Comment by SunamaZero** [comment]
I compiled this condition to assertTrue(listOpiFiles.size() <= 4)

**Comment by georgweiss** [comment]
I think commit d3d155d4486921618505bb18fdaadbdc991d9e62 is erroneous: constants for extensions were modified for OPI files, but not for script files. So listing of script files will fail as the code checks for ```endsWith("." + ext)``` (line 136).
So either the constants need to be updated, or the code should read ```endsWith(ext)```

**Comment by katysaintin** [comment]
@georgweiss @SunamaZero , Unit Test is fixed. The extension file name should not include the dot caracter. Sorry for this unintentional oversight

**Comment by georgweiss** [comment]
@katysaintin, can you please make that a PR to this repo?

**Comment by SunamaZero** [comment]
@georgweiss @katysaintin I can't thank you enough. This issue has troubled me for a long time, and my English skills are limited. Words alone can't express how much I appreciate your help.

**Comment by georgweiss** [comment]
You're welcome.

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by katysaintin** [comment]
> @georgweiss @katysaintin I can't thank you enough. This issue has troubled me for a long time, and my English skills are limited. Words alone can't express how much I appreciate your help.

@SunamaZero , you're welcome, sorry about that, we forget to test ours modifications . And thanks to our Unit Test, we found a bug in or Convertor. So thank you to you.
