### ISSUE TITLE
Drop-downs for menus or multi-entry action buttons are cut off on Linux 

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/phoebus#3156]
On Linux, drop-downs for menus or multi-entry action buttons are cut off.
You see about half of the bottom entry.

![Screenshot 2024-10-04 at 1 32 21 PM](https://github.com/user-attachments/assets/7ef77608-8c8e-41ff-b0c7-42e0324b3df1)

![image001](https://github.com/user-attachments/assets/a97be2ca-37b4-4cc0-9171-ead0ff4f9190)

![image002](https://github.com/user-attachments/assets/0c9b0fee-e132-410b-9469-b36b115153b8)

This happens with the currently used javafx 22.0.2. Did not happen with 21.0.3.

Looks like the wheels are falling off JavaFX running on Linux.
See  #3132 for drag/drop breaking the mouse.

**Comment by kasemir** [comment]
Might be related to https://bugs.openjdk.org/browse/JDK-8329821, "menus are incorrectly sized", assumed fixed in JFX 23

**Comment by kasemir** [comment]
Indeed, update to jfx 23 fixes the issue.

ButJavaFX 23 Requires JDK 21 or later and has some more changes in the release notes, https://github.com/openjdk/jfx/blob/jfx23/doc-files/release-notes-23.md

**Comment by kasemir** [comment]
Going back to the older version 21.0 of the JFX graphics library also avoids this issue and doesn't require a different JDK.

**Comment by shroffk** [comment]
For the time being I agree with going back to 21.0

Overall, I think this is a mixed bag of good and bad news... things are being fixed ( hopefully improved ) at a reasonable pace. However, it seems to push a upgrade model that might be a bit faster than we are used to or have planned for.
