### ISSUE TITLE
Save and restore take-snapshot PUT not working (broken endpoint)

### ISSUE THREAD

**Issue by JonasDevelops** [ControlSystemStudio/phoebus#3217]
I am trying to access the save and restore API from a external python script. The `take-snapshot` endpoint seems to be a good way of taking a snapshot of a predefined configuration. There seems to be a typo in the code which makes this endpoint unusable.

I have made a pull request for the small fix. After that change I could take a snapshot and restore it.

Maybe the error would have been caught if there was also a test for the put methode of the API in `services/save-and-restore/src/test/java/org/phoebus/service/saveandrestore/web/controllers/TakeSnapshotControllerTest.java`.

**Comment by georgweiss** [comment]
Feel free to add a test!
