### ISSUE TITLE
Byte monitor label color bug

### ISSUE THREAD

**Issue by DKastelic** [ControlSystemStudio/phoebus#3221]
# Expected Behavior

When the LED style of the byte monitor is set to circles instead of squares, the label color should stay constant.
![image](https://github.com/user-attachments/assets/31fea965-16b7-41cd-a448-f38f487a384d)

# Current Behavior

The label color switches based on the color of the LED, even when the label is not on the LED (circle style)
![image](https://github.com/user-attachments/assets/c4a5bde3-f18e-4d16-8ee2-e5e746e542b0)

## Steps to Reproduce

1. add a byte monitor a new display, 
2. uncheck "Square" to set the style to round LEDs, 
3. add labels to the byte monitor
4. set the PV to something like `sim://const(3)` to be able to see both ON and OFF style LEDs

**Comment by kasemir** [comment]
Thanks!
For what it's worth, this fix is not necessary for the LED widget because it will always place the text within the LED, regardless of shape. Can't remember why the LED and the Byte Monitor place the 'round' text differently; might have copied that behavior from BOY.
