### ISSUE TITLE
org.phoebus domain

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#360]
Currently, we don't own the org.phoebus domain.
Which means I cannot publish our binaries on any maven repo.

We should either look into purchasing this domain or we can refactor to use one of the existing domains like "org.epics.phoebus" or "org.controlsystemstudio.phoebus".

**Comment by georgweiss** [comment]
phoebus.org now under collaboration's control.

**Comment by shroffk** [comment]
@tmijail thanks for finding this out and helping us close 2 issues  :)
