### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#39]
The framework, app, utility, etc... modules need to be appropriately moved to different repositories so that

1.  The framework can have its own build cycle, with a more rigid release mechanism
2.  The apps/features can be developed more independently and can have a more dynamic release cycle

**Comment by claudio-rosati** [comment]
I suggest to use [Phoebus](https://github.com/shroffk/phoebus) for the UI framework, DIIRT fro the PV framework, and [KAIROS](https://github.com/ESSICS/KAIROS) for the apps/tools/features (thus becoming the new CS-Studio).

[KAIROS](https://github.com/ESSICS/KAIROS) repository was already created for this purpose when I had the idea of starting experiments using drombler-fx UI framework, but it was not populated yet, so it is free for being used. The name was carefully chosen (see the readme).
