### ISSUE TITLE
In memory logbook with markup support

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#64]
Missing requirements when creating entries:

- Markup support (Bold, Italics, Color)
- Inline attachments
- Auto correct
- Clickable links in clients
- Tables and Lists

Very nice to have
- cropping
- rotate
- annotations

**Comment by shroffk** [comment]
Markdown Writer FX (https://github.com/JFormDesigner/markdown-writer-fx)

**Comment by mvitorovic** [comment]
Java generic markup parsing library 
https://github.com/atlassian/commonmark-java

**Comment by mvitorovic** [comment]
We need to make some progress on this. IIRC Caludio was said he will do the initial work?

**Comment by claudio-rosati** [comment]
Despite my intentions, phoebus is now a very low priority task for me, being we are preparing for commissioning having a better Display BUilder (meaning also courses etc.) requires me on it almost at 100%

**Comment by shroffk** [comment]
The markdown-writer-fx is not supported with java9.

**Comment by shroffk** [comment]
Creating some prototype controls for displaying logentries

Single log entry:
![image](https://user-images.githubusercontent.com/2111304/42107202-7a10cd20-7ba4-11e8-93ed-5c29be855c30.png)

Log Entry Table:

![image](https://user-images.githubusercontent.com/2111304/42107229-8d0ad3c6-7ba4-11e8-9e6a-ef44800c2f7e.png)

**Comment by shroffk** [comment]
Ok
The time and Title can be in the same line, the body remains as is.
We can also set the Title to bold.

**Comment by shroffk** [comment]
commonmark support has been added to the olog ui clients.
currently I don't see a way to add it to the common ui without effecting other users - elog/sns logbook
closing issue
