### ISSUE TITLE
Is there any plan to integrate olog server into phoebus?

### ISSUE THREAD

**Issue by yifans** [ControlSystemStudio/phoebus#660]
Is there any plan to integrate olog server (https://github.com/Olog/olog-service) into phoebus as a server in the future, like the alarm-server and scan-server?

**Comment by shroffk** [comment]
yes,
I am working on a springboot based olog with elasticsearch as its back end. The client for this will be in phoebus...we might even consider moving the server code under services.
https://github.com/shroffk/olog-es

**Comment by forestmojo** [comment]
Wonderful. How about webopi? does phoebus support this now? I didn't see it in doc file.

**Comment by shroffk** [comment]
This is not sure yet...while we are including sprinboot service under phoebus/services the olog service pulls in a lot of dependencies.

**Comment by shroffk** [comment]
https://github.com/Olog/olog-es
