### ISSUE TITLE
Phoebus versioning

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/phoebus#720]
Starting Idea.
For the time being I hope we can use the parent version for all phoebus modules and upgrade the version number to 1.0.0 or 4.6.0(to match cs-studio)

Next Step.
Managing versions of applications and core. I am not sure what is the best policy to adopt right now?
Tentative idea:
All of core is one version - since there is interdependence and it might be best to not mix and match difference version of core modules
Each app module has it's own version, all the sub modules have to use the same version i.e. 
channel version 1.0.0
channel.util, channel.autocomplete, channel.ui all use the version 1.0.0

**Comment by kasemir** [comment]
In favor of 4.6 or 5, anything that suggests is a continuation of CS-Studio.
Maybe 7 since it's a big step; goes with EPICS 7.

Discussing version numbers is a terrific Friday topic!

**Comment by berryma4** [comment]
I vote 5 or 7 :)

**Comment by georgweiss** [comment]
What about org.epics:pbrawclient:0.0.8? Can't find it on Maven central, guess that's why it is handled separately in module install-jars. Can we get rid of that by building it and push it to Maven Central?

**Comment by kasemir** [comment]
Please add the Oracle JDBC jar to Maven central as well.

**Comment by shroffk** [comment]
hmm...I am approach murali about adding pbrawclinet

the oracle jdbc is a different story

**Comment by shroffk** [comment]
my vote is for 4.6 since we say that it is all part of the CS-Studio 4.6 release
